---
title: "Usando Regressão Linear para Explicar a votação de Deputados"
author: "Matheus Leal"
date: "10 de outubro de 2018"
output: html_document
---

```{r}
library(tidyverse)
library(here)
```


```{r}
eleicoes_data <- read_csv(here('lab-03/eleicoes_2006_e_2010.csv'),
    col_types = cols(
      ano = col_integer(),
      sequencial_candidato = col_character(),
      quantidade_doacoes = col_integer(),
      quantidade_doadores = col_integer(),
      total_receita = col_double(),
      media_receita = col_double(),
      recursos_de_outros_candidatos.comites = col_double(),
      recursos_de_pessoas_fisicas = col_double(),
      recursos_de_pessoas_juridicas = col_double(),
      recursos_proprios = col_double(),
      `recursos_de_partido_politico` = col_double(),
      quantidade_despesas = col_integer(),
      quantidade_fornecedores = col_integer(),
      total_despesa = col_double(),
      media_despesa = col_double(),
      votos = col_integer(),
      .default = col_character()))

dados <- na.omit(eleicoes_data) %>%   mutate(nome = as.character(nome),
         uf = as.character(uf),
         partido = as.character(partido),
         cargo = as.character(cargo),
         sexo = as.character(sexo),
         grau = as.character(grau),
         estado_civil = as.character(estado_civil),
         ocupacao = as.character(ocupacao)
         )

```


### 1) Um modelo de regressão múltipla com todas as variáveis é plausível para explicar a variação em y (número de votos) em 2006? Mesma pergunta para 2010. 

```{r}
eleicoes_2016 <- dados %>% filter(ano == "2006") %>% select(-nome, -sequencial_candidato, -numero_cadidato, -cargo)

```

